
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: [5480 5485 1, 5480 5485 2, 5480 5485 3, 5480 5485 4, 5480 5485 5, 5485 5490 6, 5485 5490 7, 5485 5490 8, 5485 5490 9, 5485 5490 10, 5490 5495 11, 5490 5495 12, 5490 5495 13, 5490 5495 14, 5490 5495 15, 5495 5500 16, 5495 5500 17, 5495 5500 18, 5495 5500 19, 5495 5500 20]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install
      run: |
        cd wkwk
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        sudo apt install -y ffmpeg
        sudo apt install -y google-chrome-stable
        seleniumbase install chromedriver
        sudo apt install -y xvfb
        export DISPLAY=:0
        /usr/bin/Xvfb :0 -screen 0 1024x768x24 &
        sleep 5
        xvfb-run python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
